version: 2

aliases:
  - &restore-cache-deps
      key: dependency-cache-{{ checksum "package.json" }}

  - &save-cache-deps
      key: dependency-cache-{{ checksum "package.json" }}
      paths:
        - node_modules

defaults: &defaults
  working_directory: /tmp/workspace
  docker:
    - image: circleci/node:8

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache-deps
      - run: npm install
      - save_cache: *save-cache-deps
      - run: npm run lint
      - run: npm run format:check
      - run: npm run build
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*"
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: mkdir junit
      - run:
          command: npm run test:ci
          environment:
            MOCHA_FILE: junit/test-results.xml
          when: always
      - run: npm run test:coverage
      - store_test_results:
          path: junit
      - store_artifacts:
          path: junit
          path: coverage
  deploy:
    <<: *defaults
    environment:
      GIT_AUTHOR_NAME: Ionitron
      GIT_AUTHOR_EMAIL: hi@ionicframework.com
      GIT_COMMITTER_NAME: Ionitron
      GIT_COMMITTER_EMAIL: hi@ionicframework.com
    steps:
      - add_ssh_keys:
          fingerprints:
            - "fc:0c:f5:89:bf:37:42:27:a5:c5:f0:96:0d:93:9c:3e" # ionitron user key
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: npx semantic-release

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
